"""Isolated regression tests; no reads/writes to production databases.
Run: python -m pytest audit_regression_test.py -q
"""
import csv, io, json, os, shutil, sqlite3, sys, time, types, zipfile
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from unittest.mock import patch
import pytest
os.environ['NELYIO_FORCE_SQLITE']='1'
os.environ['NELYIO_SKIP_STARTUP_DETAILS_SYNC']='1'
ROOT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT))

@pytest.fixture
def lab(tmp_path,monkeypatch):
    import app_config, supervision_context as ctx, details_store, quality_service, quality_scope
    with zipfile.ZipFile(ROOT/'audit_empty_schemas.zip') as fixtures:
        fixtures.extractall(tmp_path)
    (tmp_path/'data').mkdir()
    monkeypatch.setattr(app_config,'APP_DB',tmp_path/'TECHIN_Stock_Manager.db')
    monkeypatch.setattr(ctx,'DEFAULT_DB',tmp_path/'NELYIO_Supervision.db')
    monkeypatch.setattr(ctx,'DEFAULT_ADMIN_DB',tmp_path/'TECHIN_Stock_Manager.db')
    facade=types.ModuleType('supervision');facade.DB=ctx.DEFAULT_DB;facade.ADMIN_DB=ctx.DEFAULT_ADMIN_DB
    monkeypatch.setitem(sys.modules,'supervision',facade)
    monkeypatch.setattr(details_store,'DETAILS_DB',tmp_path/'Nelyio_Details.db')
    monkeypatch.setattr(quality_service,'QUALITY_DATA_FILE',tmp_path/'data/quality_priorities.json')
    monkeypatch.setattr(quality_service,'QUALITY_SEED_FILE',tmp_path/'absent.json')
    monkeypatch.setattr(quality_service,'QUALITY_REFERENCE_FILE',tmp_path/'absent2.json')
    monkeypatch.setattr(quality_scope,'QUALITY_DATA_FILE',tmp_path/'data/quality_priorities.json')
    monkeypatch.setattr(quality_scope,'_REVISION_FILE',tmp_path/'data/quality_scope.revision')
    quality_scope.invalidate_quality_scope_cache(touch_revision=False)
    return tmp_path

def archive(suffix, rows):
    out=io.StringIO();w=csv.DictWriter(out,fieldnames=list(rows[0]),delimiter=';');w.writeheader();w.writerows(rows)
    blob=io.BytesIO()
    with zipfile.ZipFile(blob,'w') as z:z.writestr('x.'+suffix+'.csv',out.getvalue())
    return blob.getvalue()

def inbound_row(clock='09:00:00',agent='S1001',campaign='A',**flags):
    from quality_metrics import FLAGS
    row=dict(Date='2026-09-18 '+clock,CampaignID=campaign,CampaignName='Campagne '+campaign,AgentId=agent,WaitDuration='10')
    row.update({v:'0' for v in FLAGS.values()});row['IsCall']='1';row.update({FLAGS.get(k,k):str(v) for k,v in flags.items()})
    return row

def seed(rows):
    from quality_metrics import ingest_inbound
    from supervision_db import connect
    raw=archive('Stats.INBOUND',rows)
    ingest_inbound(raw,'test.zip',1,120)
    with connect() as c:c.execute('INSERT OR REPLACE INTO call_coverage VALUES(?,?)',('2026-09-18',1))
    return raw

SCOPE={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']}

def test_pg_row_sqlite_semantics():
    from db_compat import PgRow
    r=PgRow(['key','value'],['work_start','09:15'])
    assert dict([r])=={'work_start':'09:15'}
    assert tuple(r)==('work_start','09:15')
    assert dict(r)=={'key':'work_start','value':'09:15'}
    assert r[0]=='work_start' and r['value']=='09:15'
    assert r[:]==('work_start','09:15')

def test_no_sqlite_placeholder_required(monkeypatch,tmp_path):
    import db_compat as d
    monkeypatch.setenv('NELYIO_FORCE_SQLITE','0');monkeypatch.setenv('NELYIO_DATABASE_URL','postgresql://test')
    assert not d.runtime_database_available(tmp_path/'Nelyio_Live.db')
    assert d.database_identity(tmp_path/'Nelyio_Details.db')[0]=='postgresql'
    assert not d.runtime_database_available(tmp_path/'legacy.db')

def test_pg_ddl_precision_and_identity():
    import db_compat as d
    c=d.PgConnection.__new__(d.PgConnection)
    sql,_=c._translate('CREATE TABLE test(id INTEGER PRIMARY KEY, start REAL, end REAL)')
    assert 'DOUBLE PRECISION' in sql and 'GENERATED BY DEFAULT AS IDENTITY' in sql
    assert '"end"' in sql

def test_pg_literal_percent():
    from db_compat import _replace_qmarks,_escape_psycopg_literal_percents
    sql=_escape_psycopg_literal_percents(_replace_qmarks("SELECT ? WHERE label LIKE '%stock%'"))
    assert sql=="SELECT %s WHERE label LIKE '%%stock%%'"

def test_pg_transaction_cannot_commit_swallowed_failure():
    from db_compat import PgConnection,OperationalError
    from unittest.mock import Mock
    c=PgConnection.__new__(PgConnection);c._con=Mock();c._failed=True
    with pytest.raises(OperationalError):c.commit()
    c._con.commit.assert_not_called();c._con.rollback.assert_called_once()

def test_pg_primary_key_metadata_cached():
    from db_compat import PgConnection
    from unittest.mock import MagicMock
    c=PgConnection.__new__(PgConnection);c._con=MagicMock();c.schema='supervision';c._pk_cache={}
    cur=c._con.cursor.return_value.__enter__.return_value;cur.fetchall.return_value=[('event_key',)]
    for _ in range(100):assert c._pk_columns('live_events')==['event_key']
    assert cur.execute.call_count==1

def test_pg_no_serial_probe_for_composite_pk():
    from db_compat import PgConnection
    c=PgConnection.__new__(PgConnection);c._sequence_cache={};c._pk_columns=lambda _:['a','b']
    assert c._serial_sequence('facts') is None
    assert c._serial_sequence('facts') is None

def test_source_totals_filters_and_distribution(lab):
    from quality_metrics import overview
    from quality_distributions import view
    seed([inbound_row(answered=1),inbound_row('09:10:00',agent='0',abandoned=1),
          inbound_row('10:00:00',agent='0',campaign='B',rerouted=1),
          inbound_row('19:00:00',answered=1),inbound_row('07:59:59',answered=1)])
    q=overview(SCOPE);t=q['total']
    assert (t['received'],t['treated_agent'],t['answered'],t['abandoned'],t['rerouted_no_agent'])==(3,1,1,1,1)
    assert t['qos_rate']==pytest.approx(100/3)  # 1 traité / (3 reçus - 0 clôturé - 0 racc. avant file)
    assert t['answered_wait_average']==10 and q['integrity']['ok'] is True
    dist=view(SCOPE)
    assert dist['total']=={'received':3,'treated':1,'answered':1,'abandoned':1,'closed':0,'hangup_before_queue':0,'qos':pytest.approx(100/3)}
    assert sum(x['treated'] for x in dist['hourly'])==1
    assert overview(dict(SCOPE,campaign=['B']))['total']['received']==1
    assert overview(dict(SCOPE,campaign=['missing']))['total']['qos_rate'] is None

def test_agent_alias_and_unassigned(lab):
    from quality_distributions import view
    seed([inbound_row(agent='NELYIO\\S1001',answered=1),inbound_row(agent='1001',answered=1),inbound_row(agent='0',abandoned=1)])
    assert view(dict(SCOPE,agent=['1001']))['total']['answered']==2
    assert view(dict(SCOPE,agent=['__unassigned__']))['total']['abandoned']==1

def test_missing_day_not_zero(lab):
    from quality_metrics import overview
    empty=overview(SCOPE)
    assert empty['total']['received'] is None and empty['integrity']['ok'] is None
    seed([inbound_row(answered=1)])
    partial=overview(dict(SCOPE,date_to=['2026-09-19']))
    assert partial['available_days']==1 and partial['total_days']==2

def test_reimport_idempotence_and_replacement(lab):
    from quality_metrics import overview,ingest_inbound
    raw=seed([inbound_row(answered=1)])
    assert ingest_inbound(raw,'test.zip',1,120)['updated'] is False
    assert overview(SCOPE)['total']['answered']==1
    new=archive('Stats.INBOUND',[inbound_row(answered=1),inbound_row('10:00:00',agent='0',abandoned=1)])
    ingest_inbound(new,'test.zip',1,120)
    assert overview(SCOPE)['total']['received']==2

def test_invalid_import_keeps_previous_snapshot(lab):
    from quality_metrics import overview,ingest_inbound
    seed([inbound_row(answered=1)])
    invalid=archive('Stats.INBOUND',[inbound_row(answered=1,WaitDuration='NaN')])
    with pytest.raises(ValueError):ingest_inbound(invalid,'test.zip',1,120)
    assert overview(SCOPE)['total']['answered']==1

def test_conflicting_flags_not_certified(lab):
    from quality_metrics import overview
    seed([inbound_row(answered=1,abandoned=1)])
    q=overview(SCOPE)
    assert q['integrity']['ok'] is False
    assert q['total']['double_classified']==1 and q['total']['coherence_delta']==-1

def test_negative_duration_reported_without_breaking_business_coherence(lab):
    from quality_metrics import overview
    seed([inbound_row(answered=1,WaitDuration='-1')])
    q=overview(SCOPE)
    assert q['total']['coherence_ok'] is True
    assert q['integrity']['ok'] is True
    warning=next(x for x in q['integrity']['checks'] if x['name']=='source_durations_valid')
    assert warning['ok'] is False and warning['severity']=='warning'
    assert q['total']['answered_wait_average'] is None

def test_live_stop_becomes_terminal_without_worker(lab):
    import collection_store as store
    store._SCHEMA_IDENTITIES.clear();store.init()
    now=time.time()
    sid=store.create_session({'day':'2026-09-18','start_ts':now-60,'end_ts':now+3600,
                              'start_time':'00:00','end_time':'23:59'},'audit')
    assert store.request_stop('audit')==1
    row=store.session(sid)
    assert row['status']=='stopped' and row['connection_state']=='closed'
    assert row['stop_requested']==1 and row['owner'] is None


def test_live_arm_refuses_false_active_when_external_worker_unhealthy(lab,monkeypatch):
    import collection_service,service_mode
    monkeypatch.setattr(service_mode,'external_services_enabled',lambda:True)
    monkeypatch.setattr(collection_service,'_live_service_status',lambda:{'healthy':False,'state':'dead'})
    with pytest.raises(RuntimeError,match='Service Live indisponible'):
        collection_service.arm({},'audit')


def test_agent_intervals_clipped_and_merged(lab):
    from quality_agents import ingest,view
    from supervision_db import connect
    rows=[]
    for start,duration,label in [('07:50:00',1200,'Prêt'),('08:05:00',900,'Appel entrant'),('08:20:00',600,'Pause')]:
        rows.append(dict(AgentId='S1001',ActionDate='2026-09-18 '+start,ActionDuration=str(duration),ActionName=label,IsSubAction='0',IsSubPart='0'))
    ingest(archive('Stats.AGENT',rows),'test.zip',1,120)
    seed([inbound_row(answered=1)])
    with connect() as c:c.execute('INSERT OR REPLACE INTO coverage VALUES(?,?)',('2026-09-18',1))
    q=view(SCOPE);row=q['rows'][0]
    assert row['work_seconds']==1200
    assert row['presence_seconds']==1800 and row['pause_seconds']==600
    assert row['call_average']==900 and row['handled']==1
    assert q['calls_compatible'] and q['integrity']['ok']

def test_agent_activity_fallback_restores_inbound_average_and_active_days(lab):
    from quality_agents import view
    from supervision_db import connect
    from nelyio_time import day_bounds
    seed([inbound_row(answered=1)])
    lo,_=day_bounds('2026-09-18','08:00','19:00')
    with connect() as c:
        c.execute('INSERT OR REPLACE INTO coverage VALUES(?,?)',('2026-09-18',1))
        c.execute('INSERT INTO activities(import_id,agent,name,start,end,state,kind,campaign,session) VALUES(?,?,?,?,?,?,?,?,?)',
                  (1,'1001','Agent 1',lo+3600,lo+3720,'Appel entrant','call','A',''))
        c.execute('INSERT INTO activities(import_id,agent,name,start,end,state,kind,campaign,session) VALUES(?,?,?,?,?,?,?,?,?)',
                  (1,'1002','Agent 2',lo+4200,lo+4500,'Pause','pause','A',''))
    q=view(SCOPE);rows={r['agent']:r for r in q['rows']}
    assert rows['1001']['call_average']==120 and rows['1001']['call_average_count']==1
    assert rows['1001']['worked_days']==1
    assert rows['1002']['worked_days']==1 and rows['1002']['pause_seconds']==300


def test_agent_fast_path_matches_full(lab):
    from quality_metrics import overview
    seed([inbound_row(answered=1),inbound_row(agent='S1002',answered=1)])
    assert overview(SCOPE,agents_only=True)['agents']==overview(SCOPE)['agents']

def test_live_retry_and_heartbeat_monotonic(lab):
    import live_capture
    from supervision_db import connect
    data={'source':'test','rows':[{'ts':'2026-09-18 10:00:00','line':'| ETAT | Agent 1001 | Prêt -> Déconnecté | client=A'},
                                {'ts':'2026-09-18 10:00:01','line':'NELYIO_HEARTBEAT'}]}
    assert live_capture.ingest(data,sync_details=False)['inserted']==1
    assert live_capture.ingest(data,sync_details=False)['inserted']==0
    with connect() as c:before=c.execute('SELECT heartbeat FROM health').fetchone()[0]
    live_capture.ingest({'source':'test','rows':[{'ts':'2026-09-18 09:00:00','line':'NELYIO_HEARTBEAT'}]},sync_details=False)
    with connect() as c:assert c.execute('SELECT heartbeat FROM health').fetchone()[0]==before

def test_live_accepts_added_ingestion_columns(lab):
    from supervision_db import connect
    import live_capture
    with connect() as c:
        c.execute('ALTER TABLE live_events ADD COLUMN ingest_seq INTEGER')
        c.execute('ALTER TABLE technical_signals ADD COLUMN ingest_seq INTEGER')
    data={'source':'test','rows':[{'ts':'2026-09-18 10:00:00','line':'| ETAT | Agent 1001 | Appel entrant -> Déconnecté | DECONNEXION_EN_APPEL'}]}
    assert live_capture.ingest(data,sync_details=False)['inserted']==1
    with connect() as c:assert c.execute('SELECT COUNT(*) FROM technical_signals').fetchone()[0]==1

def test_analytics_cache_invalidates_after_write(lab,monkeypatch):
    import analytics_service as a
    from supervision_db import connect
    a._CACHE.clear();a._CACHE_BYTES=0;calls=[]
    monkeypatch.setattr(a,'analytics_view',lambda q:calls.append(1) or {'n':len(calls)})
    assert a._analyze({})[1] is False
    assert a._analyze({})[1] is True
    with connect() as c:c.execute("UPDATE settings SET value='17' WHERE key='offline_seconds'")
    assert a._analyze({})[1] is False

def test_five_identical_queries_compute_once(lab,monkeypatch):
    import analytics_service as a
    a._CACHE.clear();a._CACHE_BYTES=0;calls=[]
    monkeypatch.setattr(a,'_revision',lambda:['fixed'])
    def calculate(q):calls.append(1);time.sleep(.04);return {'result':42}
    monkeypatch.setattr(a,'analytics_view',calculate)
    with ThreadPoolExecutor(max_workers=5) as pool:results=list(pool.map(lambda _:a._analyze({'day':['x']}),range(5)))
    assert len(calls)==1 and all(json.loads(x[0])=={'result':42} for x in results)

def test_pg_distribution_zero_contract():
    src=(ROOT/'postgres_migrate.py').read_text()
    assert "IN ('', '0', 'S0') THEN ''" in src

@pytest.mark.parametrize('day,hours',[('2026-03-29',23),('2026-10-25',25),('2026-09-18',24)])
def test_dst_day_bounds(day,hours):
    from nelyio_time import day_bounds
    a,b=day_bounds(day);assert b-a==hours*3600

def test_details_cache_revision(lab):
    import details_store as d
    d.init()
    with d.connect_details() as c:
        c.execute('BEGIN');a=d._read_cache_key(c,'audit',{})
    with d.connect_details() as c:
        c.execute("INSERT OR REPLACE INTO active_days(day,source_kind,source_import_id,updated_at) VALUES('2026-09-18','export',1,'now')")
    with d.connect_details() as c:
        c.execute('BEGIN');b=d._read_cache_key(c,'audit',{})
    assert a is not None and a!=b

def test_pg_aggregates_serialize_without_rounding_counts():
    from db_compat import PgRow
    from decimal import Decimal
    row=PgRow(['count','average'],[Decimal('9007199254740993'),Decimal('3.5')])
    assert json.loads(json.dumps(dict(row)))=={'count':9007199254740993,'average':3.5}

def test_empty_views_and_json(lab):
    from calls import calls_view
    from support_views import view,support_view
    from analytics import analytics_view
    from quality_precision_check import run
    for result in [calls_view(SCOPE),view(SCOPE),support_view(SCOPE),analytics_view(SCOPE),run('2026-09-18')]:
        assert isinstance(json.loads(json.dumps(result)),dict)

def test_pg_call_aggregates_use_explicit_cases():
    src=(ROOT/'calls.py').read_text()
    assert 'SUM(CASE WHEN duration<0' in src
    assert 'SUM(conversation>0)' not in src

def test_quality_gate_same_hours(lab):
    from quality_agents import ingest
    from supervision_db import connect
    from quality_precision_check import run
    ingest(archive('Stats.AGENT',[dict(AgentId='1001',ActionDate='2026-09-18 08:00:00',ActionDuration='3600',ActionName='Prêt',IsSubAction='0',IsSubPart='0')]),'test.zip',1,120)
    seed([inbound_row(answered=1),inbound_row('19:00:00',answered=1)])
    with connect() as c:c.execute("INSERT OR REPLACE INTO coverage VALUES('2026-09-18',1)")
    result=run('2026-09-18')
    assert result['ok'] is True and result['service']['handled']==1

def test_support_notes_batched(lab,monkeypatch):
    from supervision_db import connect
    from support_views import view
    from nelyio_time import day_bounds
    import db_compat
    lo,_=day_bounds('2026-09-18')
    with connect() as c:
        c.execute("INSERT INTO coverage VALUES('2026-09-18',1)")
        for n in range(1,21):
            c.execute('INSERT INTO activities(id,import_id,agent,name,start,end,state,kind,campaign,session) VALUES(?,?,?,?,?,?,?,?,?,?)',
                      (n,1,'1001','Test',lo+9*3600+n*60,lo+9*3600+n*60+30,'Prêt','ready','',''))
    original=db_compat.connect;queries=[]
    def traced(*a,**kw):
        c=original(*a,**kw);c.set_trace_callback(queries.append);return c
    monkeypatch.setattr(db_compat,'connect',traced)
    result=view(dict(SCOPE,mode=['history']))
    assert len(result['rows'])==20
    assert len([q for q in queries if 'SELECT * FROM notes WHERE' in q])==1

def test_full_import_and_duplicate(lab):
    from export_import import import_export
    from supervision_db import connect
    row=dict(AgentId='1001',ActionDate='2026-09-18 09:00:00',ActionDuration='3600',ActionName='Prêt',IsSubAction='0',IsSubPart='0')
    raw=archive('Stats.AGENT',[row])
    result=import_export(raw,'SIMPLIFY2_2026-09-18.zip',120,'audit')
    assert result['rows']==1
    assert result['status']=='completed', result.get('steps')
    result=import_export(raw,'SIMPLIFY2_2026-09-18.zip',120,'audit')
    with connect() as c:
        assert c.execute('SELECT COUNT(*) FROM activities').fetchone()[0]==1
        assert c.execute('SELECT COUNT(*) FROM imports').fetchone()[0]==1


def test_group_filter_keeps_agent_durations_and_call_average(lab):
    """A file-based group must filter agents without zeroing Stats.AGENT durations."""
    from quality_agents import ingest, view
    from supervision_db import connect
    import quality_scope
    rows=[]
    for agent,start,duration,label in [
        ('S1001','08:10:00',600,'Prêt'),
        ('S1001','08:20:00',300,'Appel entrant'),
        ('S1001','08:25:00',180,'Pause'),
        ('S1002','08:10:00',1200,'Prêt'),
        ('S1002','08:30:00',900,'Appel entrant'),
    ]:
        rows.append(dict(AgentId=agent,ActionDate='2026-09-18 '+start,ActionDuration=str(duration),
                         ActionName=label,IsSubAction='0',IsSubPart='0'))
    ingest(archive('Stats.AGENT',rows),'group-duration.zip',1,120)
    seed([inbound_row(agent='S1001',answered=1),inbound_row('09:30:00',agent='S1002',answered=1)])
    with connect() as c:
        c.execute('INSERT OR REPLACE INTO coverage VALUES(?,?)',('2026-09-18',1))
    scope={
        'basis':'configured_files',
        'groups':[{'id':'10','name':'IMG2','service_name':'IMAGERIE','line_ids':[101], 'campaign_ids':['A'],
                   'member_agent_ids':['1001'],'file_count':1,'member_count':1},
                  {'id':'11','name':'IMG3','service_name':'IMAGERIE','line_ids':[102], 'campaign_ids':['B'],
                   'member_agent_ids':['1001','1002'],'file_count':1,'member_count':2}],
        'agent_files':{'1001':[101,102],'1002':[102]},
        'campaign_to_files':{'A':[{'line_id':101,'line_name':'File IMG2'}]},
    }
    with patch.object(quality_scope,'load_quality_file_scope',return_value=scope):
        q=view(dict(SCOPE,group=['10']))
        service_q=view(dict(SCOPE,service=['IMAGERIE']))
    assert q['group']=='10' and q['group_name']=='IMG2'
    assert [r['agent'] for r in q['rows']]==['1001']
    row=q['rows'][0]
    assert row['work_seconds']==900
    assert row['pause_seconds']==180
    assert row['call_average']==300 and row['handled']==1
    assert q['summary']['work_seconds']==900
    assert service_q['service']=='IMAGERIE' and {r['agent'] for r in service_q['rows']}=={'1001','1002'}
    assert service_q['summary']['agent_count']==2


def test_quality_service_filter_unions_subgroups_without_cross_service_calls(lab):
    import quality_scope
    from quality_metrics import overview
    from quality_distributions import view as distribution_view
    seed([inbound_row(agent='S1001',campaign='A',answered=1),
          inbound_row('09:10:00',agent='S1002',campaign='B',answered=1),
          inbound_row('09:20:00',agent='S1003',campaign='C',answered=1)])
    scope={'basis':'configured_files','groups':[
        {'id':'10','name':'IMG2','service_name':'IMAGERIE','line_ids':[101],'campaign_ids':['A'],
         'member_agent_ids':['1001'],'file_count':1,'member_count':1,'assignment_counts':{}},
        {'id':'11','name':'IMG3','service_name':'IMAGERIE','line_ids':[102],'campaign_ids':['B'],
         'member_agent_ids':['1001','1002'],'file_count':1,'member_count':2,'assignment_counts':{}},
        {'id':'20','name':'MED2','service_name':'MEDICAL','line_ids':[201],'campaign_ids':['C'],
         'member_agent_ids':['1003'],'file_count':1,'member_count':1,'assignment_counts':{}},
    ]}
    with patch.object(quality_scope,'load_quality_file_scope',return_value=scope):
        q=overview(dict(SCOPE,service=['IMAGERIE']))
        dist=distribution_view(dict(SCOPE,service=['IMAGERIE']))
    assert q['service']=='IMAGERIE' and q['total']['received']==2 and q['total']['treated_agent']==2
    assert {x['campaign'] for x in q['campaign_choices']}=={'A','B'}
    assert dist['service']=='IMAGERIE' and dist['total']['received']==2 and dist['total']['treated']==2


def test_group_workspace_projects_files_to_active_agents_and_campaigns(lab):
    """Administration Group workspace must show the same file scope as KPI filters."""
    import app_config, quality_service, quality_scope
    from group_workspace import workspace
    import sqlite3 as raw_sqlite
    raw={
        'version':3,'source_type':'import','source_file':'SIMPLIFY2.test.zip','source_day':'2026-09-18',
        'campaigns':[{'campaign_id':'C1','campaign_name':'Campagne 1'}],
        'queues':[{'line_id':101,'line_name':'File IMG2','campaign_ids':['C1']}],
        'observations':[],
        'agents':[
            {'agent_id':'1001','agent_first_name':'A','agent_last_name':'One','queues':[{
                'line_id':101,'line_name':'File IMG2','activation_state':'active','assignment_source':'configured'}]},
            {'agent_id':'1002','agent_first_name':'B','agent_last_name':'Two','queues':[{
                'line_id':101,'line_name':'File IMG2','activation_state':'inactive','assignment_source':'configured'}]},
        ],
        'scope_sources':{'agent_queues':{'day':'2026-09-18','file':'SIMPLIFY2.test.zip'}},
    }
    quality_service.save_quality_snapshot(raw)
    con=raw_sqlite.connect(str(app_config.APP_DB))
    try:
        gid=con.execute("INSERT INTO user_groups(name,description,created_by,updated_by) VALUES('IMG2','','test','test')").lastrowid
        con.execute("INSERT INTO quality_group_meta(group_id,supervision_id,source_note) VALUES(?,?,?)",(gid,'2','group.har'))
        con.execute("INSERT INTO quality_group_lines(group_id,line_id,created_by) VALUES(?,?,?)",(gid,101,'test'))
        con.commit()
    finally:
        con.close()
    quality_scope.invalidate_quality_scope_cache()
    out=workspace();g=next(x for x in out['groups'] if x['name']=='IMG2')
    assert g['scope_line_count']==1
    assert g['scope_agent_count']==1 and g['automatic_agent_ids']==['1001']
    assert g['scope_campaign_count']==1
    assert [(c['campaign_id'],c['name']) for c in g['derived_campaigns']]==[('C1','Campagne 1')]
    assert out['assignment_source_available'] is True


def test_suspicious_calls_preserve_call_level_uncertainty(lab):
    """Suspect calls must use Call ID facts and never infer a caller hangup."""
    from supervision_db import connect, config, init
    from supervision_utils import selected_bounds
    from suspicious_calls import view
    init()
    qs={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']}
    lo,_=selected_bounds('2026-09-18',config(),qs,'0')
    calls=[
        (1,'short-agent','I1',lo+3600,'1',5,4,1,'0611111111','','','','1001','1001','C1','',0,0,0,1),
        (1,'wait-half','I2',lo+7200,'1',20,8,12,'0622222222','','','','1002','1002','C2','',0,0,0,0),
        (1,'technical','I3',lo+10800,'1',40,35,1,'0633333333','','','','1003','1003','C3','',0,0,0,0),
        (1,'normal-agent','I4',lo+14400,'1',120,110,5,'0644444444','','','','1004','1004','C4','',0,0,0,1),
    ]
    details=[
        (1,'short-agent',5,1,1,'501','501','C1','C1',''),
        (1,'wait-half',20,12,12,'502','502','C2','C2',''),
        (1,'technical',40,1,1,'503','503','C3','C3',''),
        (1,'normal-agent',120,5,5,'504','504','C4','C4',''),
    ]
    with connect() as c:
        c.executemany('INSERT INTO phone_calls VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',calls)
        c.executemany('INSERT INTO phone_call_details VALUES(?,?,?,?,?,?,?,?,?,?)',details)
        c.execute('INSERT INTO quality_call_holds(import_id,call_id,hold_duration,hold_segments) VALUES(?,?,?,?)',(1,'wait-half',12,1))
        c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',('2026-09-18',1))
        c.execute('INSERT INTO technical_signals(signal_key,source,agent,start,category,detail) VALUES(?,?,?,?,?,?)',
                  ('t1','SIMPLIFY2','1003',lo+10805,'disconnect','signal test'))
    short=view(dict(qs,category=['short']))
    assert short['count']==1 and short['rows'][0]['call_id']=='short-agent'
    assert short['rows'][0]['finish_origin']=='agent'
    assert short['rows'][0]['ani']!='0611111111' and short['rows'][0]['ani_masked'] is True
    wait=view(dict(qs,category=['hold50']))
    assert wait['count']==1 and wait['rows'][0]['call_id']=='wait-half'
    assert wait['rows'][0]['hold_ratio']==60.0 and wait['rows'][0]['hold_duration']==12
    assert wait['rows'][0]['finish_origin']=='indeterminate'
    # Legacy bookmarks retain the corrected semantics.
    assert view(dict(qs,category=['wait50']))['count']==1
    caller=view(dict(qs,category=['end_caller']))
    assert caller['count']==0 and caller['capabilities']['end_by_caller'] is False
    all_suspects=view(dict(qs,category=['all']))
    assert all_suspects['count']==3
    assert {x['agent'] for x in all_suspects['agent_summary']}=={'1001','1002','1003'}
    ended=view(dict(qs,category=['end_agent']))
    assert ended['count']==2 and {x['call_id'] for x in ended['rows']}=={'short-agent','normal-agent'}
    technical=view(dict(qs,category=['technical'],_show_ani=['1']))
    assert technical['count']==1 and technical['rows'][0]['call_id']=='technical'
    assert technical['rows'][0]['ani']=='0633333333' and technical['rows'][0]['ani_masked'] is False
    assert technical['rows'][0]['technical_signals'][0]['category']=='disconnect'


def test_suspicious_calls_exclude_transfer_consultation_heuristics(lab):
    from supervision_db import connect, config, init
    from supervision_utils import selected_bounds
    from suspicious_calls import view
    init();qs={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']}
    lo,_=selected_bounds('2026-09-18',config(),qs,'0')
    with connect() as c:
        c.execute('INSERT INTO phone_calls VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
          (1,'complex-short','IX',lo+3600,'1',5,4,0,'0611111111','','','','1001','1001','C1','',0,0,0,0))
        c.execute('INSERT INTO phone_call_details VALUES(?,?,?,?,?,?,?,?,?,?)',
          (1,'complex-short',5,0,0,'501','501','C1','C1','1002'))
        c.execute('INSERT INTO quality_call_holds(import_id,call_id,hold_duration,hold_segments) VALUES(?,?,?,?)',(1,'complex-short',4,1))
        c.execute('INSERT INTO phone_call_relations VALUES(?,?,?,?,?)',(1,'complex-short','parent','3','Internal consultation'))
        c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',('2026-09-18',1))
    assert view(dict(qs,category=['short']))['count']==0
    assert view(dict(qs,category=['hold50']))['count']==0
    all_rows=view(dict(qs,category=['all']))
    assert all_rows['count']==0



def test_recording_folder_payload_and_low_content_detection(lab):
    from recording_sizes import parse_folder_payload, extract_seed
    from supervision_db import connect, config, init
    from supervision_utils import selected_bounds
    from suspicious_calls import view
    payload='{"BasePath":"RECORD","FolderList":[],"FileList":[{"Name":"1001#20260918#090000#MEDIA-LOW.wav","Size":120000}]}'
    folders,files=parse_folder_payload(payload)
    assert folders==[] and files[0]['indice']=='MEDIA-LOW' and files[0]['size_bytes']==120000
    seed=extract_seed(['https://fr06-supervision.vocalcom.com/hermes360/Supervision/changes.ashx?act=folder_info&uid=U1&idCompany=231&extension=%2A.wav&basePath=RECORD&subPath=12139733%5C2026%5C08%5C24%5C1079&filters='])
    assert seed and seed['root']=='12139733' and seed['idCompany']=='231' and seed['uid']=='U1'
    init();qs={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']}
    lo,_=selected_bounds('2026-09-18',config(),qs,'0')
    calls=[
      (1,'media-low','MEDIA-LOW',lo+3600,'1',60,60,0,'0611111111','','','','1001','1001','C1','',0,0,0,0),
      (1,'media-normal','MEDIA-OK',lo+7200,'1',60,60,0,'0622222222','','','','1001','1001','C1','',0,0,0,0),
      (1,'media-transfer','MEDIA-X',lo+10800,'1',60,60,0,'0633333333','','','','1001','1001','C1','',0,0,0,0),
    ]
    details=[
      (1,'media-low',60,0,0,'501','501','C1','C1',''),
      (1,'media-normal',60,0,0,'501','501','C1','C1',''),
      (1,'media-transfer',60,0,0,'501','501','C1','C1','1002'),
    ]
    with connect() as c:
        c.executemany('INSERT INTO phone_calls VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',calls)
        c.executemany('INSERT INTO phone_call_details VALUES(?,?,?,?,?,?,?,?,?,?)',details)
        c.executemany('INSERT INTO call_recording_sizes(indice,size_bytes) VALUES(?,?)',[
          ('MEDIA-LOW',120000),('MEDIA-OK',480000),('MEDIA-X',120000),
        ])
        c.execute('INSERT INTO phone_call_relations VALUES(?,?,?,?,?)',(1,'media-transfer','parent','3','Internal consultation'))
        c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',('2026-09-18',1))
    low=view(dict(qs,category=['low_content']))
    assert low['count']==1 and low['rows'][0]['call_id']=='media-low'
    assert low['rows'][0]['recording_size_bytes']==120000
    assert low['rows'][0]['media_density_bps']==2000.0
    assert low['rows'][0]['media_coverage_pct']==25.0
    assert 'Contenu très faible / size' in low['rows'][0]['reasons']
    assert low['capabilities']['media_size'] is True


def test_suspicious_ui_uses_in_call_hold_not_queue_wait():
    suspects=(ROOT/'static'/'suspicious-calls.js').read_text(encoding='utf-8')
    assert 'Mise en attente ≥ 30 %' in suspects and 'Mise en attente ≥ 50 %' in suspects
    assert 'Attente initiale ≥ 30 %' not in suspects and 'Attente initiale ≥ 50 %' not in suspects
    assert 'ODRelations' in suspects and 'Contenu faible / size anormal' in suspects


def test_short_calls_are_centralized_in_suspicious_ui():
    """The dedicated suspect page owns the <10s display; Quality agents must not duplicate it."""
    quality=(ROOT/'static'/'quality-activity.js').read_text(encoding='utf-8')
    suspects=(ROOT/'static'/'suspicious-calls.js').read_text(encoding='utf-8')
    index=(ROOT/'index.html').read_text(encoding='utf-8')
    assert 'Appels < 10 s' not in quality and 'Appels &lt; 10 s' not in quality
    assert 'Appels < 10 s' in suspects
    assert '#suspicious-calls' in index and '>Analytiques<' in index


def _seed_quality_day(day, import_id, treated, abandoned):
    from quality_metrics import ingest_inbound
    from supervision_db import connect
    rows=[]
    for i in range(treated):
        r=inbound_row('09:00:00',agent='S1001',answered=1);r['Date']=day+' 09:00:00';rows.append(r)
    for i in range(abandoned):
        r=inbound_row('09:30:00',agent='S0',abandoned=1);r['Date']=day+' 09:30:00';rows.append(r)
    raw=archive('Stats.INBOUND',rows)
    ingest_inbound(raw,f'SIMPLIFY2.{day}.zip',import_id,120)
    with connect() as c:c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',(day,import_id))


def _seed_file_calls(day,import_id,file_id,received,abandoned,wait=20,agent='S1001'):
    from nelyio_time import local_wall_timestamp
    from supervision_db import connect
    start=local_wall_timestamp(day,9,0)
    with connect() as c:
        for i in range(received):
            lost=i<abandoned;call_id=f'{day}-{file_id}-{i}'
            assigned='' if lost else agent
            c.execute('''INSERT INTO phone_calls(import_id,call_id,indice,start,call_type,duration,conversation,wait,ani,dnis,outtel,outdialed,
                         first_agent,last_agent,campaign,end_reason,no_agent,abandon,closed,end_by_agent)
                         VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
                      (import_id,call_id,str(i),start+i,'1',60,40,wait,'0600000000','','','',assigned,assigned,'A','',1 if lost else 0,1 if lost else 0,0,0))
            c.execute('''INSERT INTO phone_call_details(import_id,call_id,call_duration,wait_initial,total_wait,first_queue,last_queue,first_campaign,last_campaign,last_transfer)
                         VALUES(?,?,?,?,?,?,?,?,?,?)''',
                      (import_id,call_id,60,wait,wait,str(file_id),str(file_id),'A','A',''))


def test_pilotage_uses_same_weekday_baseline_and_no_causal_claim(lab):
    import app_db
    from supervision_db import init
    from pilotage_quality import view,save_action,list_actions,compare_action,_resolve_scope
    init();app_db.ensure_schema()
    for iid,day in enumerate(['2026-08-21','2026-08-28','2026-09-04','2026-09-11'],1):
        _seed_quality_day(day,iid,90,10)
        _seed_file_calls(day,iid,'501',40,2,20)
    _seed_quality_day('2026-09-18',5,70,30)
    _seed_file_calls('2026-09-18',5,'501',50,15,90)
    _seed_file_calls('2026-09-18',5,'999',2,1,600)
    out=view({'day':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00'],'min_volume':['30']})
    assert out['baseline_status']=='ready' and len(out['baseline_days'])==4
    assert round(out['baseline']['abandonment_rate'],1)==10.0
    assert round(out['current']['abandonment_rate'],1)==30.0
    assert round(out['current']['qos'],1)==70.0 and round(out['baseline']['qos'],1)==90.0
    codes={x['code'] for x in out['signals']}
    assert 'abandon_high' in codes and 'qos_low' in codes and len(out['signals'])<=5
    assert all(x['certainty']=='observation' for x in out['signals'])
    assert _resolve_scope([{'id':'1','service_name':'MEDICAL','member_agent_ids':['1001','1002'],'campaign_ids':['A']},
                           {'id':'2','service_name':'MEDICAL','member_agent_ids':['1002','1003'],'campaign_ids':['B']}],
                          'MEDICAL','')[1]==['1001','1002','1003']
    saved=save_action({'title':'Renforcer couverture','application_date':'2026-09-11','status':'Appliqué',
                       'context':{'time_from':'08:00','time_to':'19:00'}},'tester')
    assert list_actions()['rows'][0]['id']==saved['id']
    verify=save_action({'title':'Contrôler après action','application_date':'2026-09-18','status':'À vérifier'},'tester')
    refined=view({'day':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00'],'min_volume':['30'],'granularity':['30']})
    assert refined['granularity']==30 and len(refined['hourly'])==2
    assert refined['hourly'][0]['label']=='09:00–09:30' and refined['hourly'][0]['wait_median']==10
    assert refined['hourly'][0]['treated_per_agent']==70
    files=refined['files_to_investigate']
    assert files['status']=='ready' and files['source']=='ODCalls.FirstQueue'
    assert files['rows'][0]['file_id']=='501' and files['rows'][0]['abandoned']==15
    assert all(x['file_id']!='999' for x in files['rows'])
    assert files['rows'][0]['baseline_status']=='ready' and files['rows'][0]['baseline']['abandoned']==2
    assert any('historique comparable' in x for x in files['rows'][0]['factors'])
    assert any(x['id']==verify['id'] for x in refined['actions_to_verify'])
    comp=compare_action({'id':[str(saved['id'])]})
    assert comp['status']=='ready' and comp['before_day']=='2026-09-04' and comp['after_day']=='2026-09-18'
    assert 'cause' not in comp['message'].lower()
    assert 'n’établit pas' in comp['causality']
    file_action=save_action({'title':'Renforcer file 501','file_id':'501','application_date':'2026-09-11','status':'Appliqué',
                             'context':{'time_from':'08:00','time_to':'19:00'}},'tester')
    file_comp=compare_action({'id':[str(file_action['id'])]})
    assert file_comp['status']=='ready' and file_comp['before']['abandoned']==2 and file_comp['after']['abandoned']==15


def test_pilotage_requires_two_comparable_days(lab):
    from supervision_db import init
    from pilotage_quality import view
    init();_seed_quality_day('2026-09-18',1,90,10)
    out=view({'day':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']})
    assert out['baseline_status']=='insufficient' and out['signals']==[]


def test_pilotage_respects_policy_and_declaration_exclusions(lab):
    import app_db
    from supervision_db import init
    from policy_admin import save_policy
    from declaration_admin import save_declaration
    from pilotage_quality import view
    init();app_db.ensure_schema()
    _seed_quality_day('2026-09-04',1,90,10)
    _seed_quality_day('2026-09-11',2,90,10)
    _seed_quality_day('2026-09-18',3,70,30)
    save_policy({'name':'Exclusion test abandon','policy_type':'AUTORISATION','enabled':True,
                 'date_from':'2026-09-18','date_to':'2026-09-18','time_from':'09:30','time_to':'09:45',
                 'actions':{'exclude_statistics':True},'modules':['analytics'],
                 'targets':[{'target_type':'GLOBAL','target_key':'*'}]},'tester')
    save_declaration({'declaration_type':'REUNION','date':'2026-09-18','start_time':'08:55','duration_minutes':'15',
                      'targets':[{'target_type':'AGENT','target_key':'1001'}],'comment':'Réunion test'},'tester')
    out=view({'day':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00'],'min_volume':['30']})
    assert out['current']['received']==0
    assert out['current']['governance_excluded']==100
    assert out['signals']==[]
    gov=out['reliability']['governance']
    assert gov['active'] is True and gov['policies']==1 and gov['declarations']==1 and gov['excluded_calls']==100
    assert sum(x['count'] for x in gov['reasons'])==100


def test_pilotage_ui_exposes_progressive_analysis_controls():
    js=(ROOT/'static'/'pilotage-quality.js').read_text(encoding='utf-8')
    assert 'Analyser' in js
    assert 'Actions à vérifier' in js
    assert 'Files à investiguer' in js
    assert '30 minutes' in js and 'Attente moy.' in js and 'Médiane' in js
    assert 'Traités / agent' in js

def _seed_live_observations(tmp_path,monkeypatch):
    import collection_store as store
    from nelyio_time import local_wall_timestamp
    live_db=tmp_path/'Nelyio_Live.db'
    monkeypatch.setattr(store,'db_path',lambda:live_db)
    store._SCHEMA_IDENTITIES.clear();store.init()
    clock=local_wall_timestamp('2026-09-18',10,0)
    settings={'day':'2026-09-18','start_ts':clock-3600,'end_ts':clock+3600,'start_time':'09:00','end_time':'11:00'}
    sid=store.create_session(settings,'audit',clock=clock-120)
    def push(stamp,rid,events):
        result=store.record_response(sid,'simplify',stamp,rid,'digest-'+rid,
            {'recognized':len(events),'rejected':0,'events':events,'valid':True})
        assert result['accepted'] is True
    push(clock-20,'r1',[
        {'type':'agent','entity':'1001','payload':{'agent':'1001','first_name':'Alice','last_name':'Test','queues':['12']}},
        {'type':'agent','entity':'1002','payload':{'agent':'1002','first_name':'Bob','last_name':'Test','queues':['12']}},
        {'type':'agent','entity':'1003','payload':{'agent':'1003','first_name':'Chloe','last_name':'Test','queues':[]}},
        {'type':'state','entity':'1001','payload':{'agent':'1001','state':'Prêt','old_state':'','initial':True,'line_id':'12','campaign':'CAB'}},
        {'type':'state','entity':'1002','payload':{'agent':'1002','state':'Prêt','old_state':'','initial':True,'line_id':'12','campaign':'CAB'}},
        {'type':'state','entity':'1003','payload':{'agent':'1003','state':'Déconnecté','old_state':'','initial':True,'line_id':'','campaign':''}},
    ])
    call_payload={'agent':'1001','context':-1,'state':'Inbound call','line_id':'12','line_name':'File 12','campaign':'CAB',
                  'phone':'0612345678','phone_status':'available','source_function':'UpAgtTState','source_counters':{},
                  'timing_basis':'receipt_observation','parser_version':'V56.3-live-1','observation_ref':'1001-1','phase':'observing','partial_start':False}
    push(clock-5,'r2',[
        {'type':'state','entity':'1001','payload':{'agent':'1001','state':'Inbound call','old_state':'Prêt','initial':False,'line_id':'12','campaign':'CAB'}},
        {'type':'call_observation','entity':'1001','payload':call_payload},
    ])
    return store,clock,sid


def test_live_user_views_use_current_spool_without_inventing_metrics(lab,monkeypatch):
    store,clock,_=_seed_live_observations(lab,monkeypatch)
    snap=store.live_supervision_snapshot(clock=clock)
    assert snap['health']['fresh'] is True and snap['health']['state']=='live'
    assert snap['kpi']['agents_known']==3 and snap['kpi']['connected']==2
    assert snap['kpi']['in_call']==1 and snap['kpi']['available']==1
    assert snap['kpi']['current_calls']==1 and snap['kpi']['calls_waiting'] is None
    alice=next(r for r in snap['agents'] if r['agent']=='1001')
    assert alice['kind']=='call' and alice['current_call']['reference']=='1001-1' and alice['ticking'] is True
    assert snap['capabilities']['call_id'] is False and snap['capabilities']['calls_waiting'] is True

    # Without the independent ANI permission, the phone is masked and is not
    # part of the generic search haystack (otherwise exact-number probing would
    # still leak whether a caller exists).
    hidden_lookup=store.live_call_search({'window':['30m'],'q':['0612']},clock=clock,show_phone=False)
    assert hidden_lookup['count']==0
    masked=store.live_call_search({'window':['30m'],'reference':['1001-1']},clock=clock,show_phone=False)
    assert masked['count']==1 and masked['rows'][0]['phone']!='0612345678' and masked['rows'][0]['phone_masked'] is True
    assert masked['rows'][0]['call_id'] is None and masked['rows'][0]['wait'] is None
    full=store.live_call_search({'window':['30m'],'q':['0612']},clock=clock,show_phone=True)
    assert full['count']==1 and full['rows'][0]['phone']=='0612345678'
    assert full['reference_label']=='Référence Live' and full['capabilities']['end_origin'] is False


def test_live_user_views_freeze_when_collection_is_stale(lab,monkeypatch):
    store,clock,_=_seed_live_observations(lab,monkeypatch)
    stale=store.live_supervision_snapshot(clock=clock+40)
    assert stale['health']['fresh'] is False and stale['health']['state']=='delay'
    assert stale['kpi']['current_calls'] is None
    alice=next(r for r in stale['agents'] if r['agent']=='1001')
    assert alice['ticking'] is False and alice['current_call']['status']=='unconfirmed'
    search=store.live_call_search({'window':['in_progress']},clock=clock+40,show_phone=True)
    assert search['rows'][0]['status']=='unconfirmed'


def test_live_external_worker_failure_freezes_fresh_session(lab,monkeypatch):
    store,clock,_=_seed_live_observations(lab,monkeypatch)
    import service_mode, service_state
    monkeypatch.setattr(service_mode,'external_services_enabled',lambda:True)
    monkeypatch.setattr(service_state,'public_status',lambda:{'services':[{'service':'live','healthy':False,'state':'stopped','age_seconds':30.0,'build_match':True}]})
    snap=store.live_supervision_snapshot(clock=clock)
    assert snap['health']['state']=='worker_down' and snap['health']['fresh'] is False
    assert snap['health']['worker_healthy'] is False and snap['health']['worker_state']=='stopped'
    assert snap['kpi']['current_calls'] is None
    alice=next(r for r in snap['agents'] if r['agent']=='1001')
    assert alice['ticking'] is False and alice['current_call']['status']=='unconfirmed'


def test_live_navigation_is_separate_from_collector_admin():
    html=(ROOT/'index.html').read_text(encoding='utf-8')
    js=(ROOT/'static/live-views.js').read_text(encoding='utf-8')
    assert 'data-nav-section="live"' in html
    assert 'href="#live-supervision"' in html and 'href="#live-search"' in html
    assert 'Collecteur Live' in html and '>Live Nelyio<' not in html
    assert "rc29SortHeader(tableKey,'waiting','Attente','number')" in js
    assert 'Appels en attente instantanés' in js
    assert 'Call ID : </strong>non disponible' in js or 'Call ID :</strong> non disponible' in js

def test_live_allows_only_one_armed_session_even_before_worker_claim(lab,monkeypatch):
    import collection_store as store
    from nelyio_time import local_wall_timestamp
    monkeypatch.setattr(store,'db_path',lambda:lab/'Nelyio_Live_single.db')
    store._SCHEMA_IDENTITIES.clear();store.init()
    clock=local_wall_timestamp('2026-09-18',10,0)
    settings={'day':'2026-09-18','start_ts':clock-60,'end_ts':clock+3600,'start_time':'09:59','end_time':'11:00'}
    first=store.create_session(settings,'audit',clock=clock,owner=None)
    with pytest.raises(RuntimeError,match='deja en cours ou programmee'):
        store.create_session(settings,'audit2',clock=clock+1,owner=None)
    assert store.session(first)['status']=='armed'


def test_historical_calls_ani_permission_masks_rows(lab):
    from supervision_db import connect, config, init
    from supervision_utils import selected_bounds
    from calls import calls_view
    init()
    qs={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00']}
    lo,_=selected_bounds('2026-09-18',config(),qs,'0')
    with connect() as c:
        c.execute('''INSERT INTO phone_calls(import_id,call_id,indice,start,call_type,duration,conversation,wait,ani,dnis,outtel,outdialed,
                     first_agent,last_agent,campaign,end_reason,no_agent,abandon,closed,end_by_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''',
                  (1,'ANI-1','I1',lo+60,'1',60,45,5,'0612345678','','','','1001','1001','C1','',0,0,0,0))
        c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',('2026-09-18',1))
    masked=calls_view(dict(qs,_show_ani=['0']))
    assert masked['count']==1 and masked['rows'][0]['ani']!='0612345678' and masked['rows'][0]['ani_masked'] is True
    full=calls_view(dict(qs,_show_ani=['1']))
    assert full['rows'][0]['ani']=='0612345678' and full['rows'][0]['ani_masked'] is False


def test_duplicate_reimport_enriches_phone_call_details_without_duplicate_calls(lab):
    """Fresh/legacy DBs self-migrate, then a replay enriches without duplicating calls."""
    from export_import import import_export
    from supervision_db import connect, init
    init()
    # Simulate a database created by a build predating the extension table.
    # The dedicated Importer must migrate it even when the Web process has not
    # initialized the schema first.
    with connect() as c:
        c.execute('DROP TABLE phone_call_details')
    stats_fields=['AgentId','AgentFirstName','AgentLastName','ActionDate','ActionDuration','ActionName','IsSubAction','IsSubPart','CampaignName','SessionID','DistributionGroup']
    calls_fields=['ID','DateUTC','Indice','CallType','Duration','CallDuration','ConvDuration','WaitDuration','TotalWaitDuration',
                  'ANI','DNIS','OutTel','OutDialed','FirstAgent','LastAgent','FirstQueue','LastQueue','FirstCampaign','LastCampaign',
                  'LastTransfer','EndReason','NoAgent','Abandon','Closed','EndByAgent']
    stats=io.StringIO(); w=csv.DictWriter(stats,fieldnames=stats_fields,delimiter=';'); w.writeheader(); w.writerow({
        'AgentId':'1001','AgentFirstName':'A','AgentLastName':'B','ActionDate':'2026-09-18 09:00:00','ActionDuration':'60',
        'ActionName':'Ready','IsSubAction':'0','IsSubPart':'0','CampaignName':'Campagne A','SessionID':'1','DistributionGroup':''})
    calls=io.StringIO(); w=csv.DictWriter(calls,fieldnames=calls_fields,delimiter=';'); w.writeheader(); w.writerow({
        'ID':'CALL-1','DateUTC':'2026-09-18 07:00:00','Indice':'I1','CallType':'1','Duration':'120','CallDuration':'110',
        'ConvDuration':'90','WaitDuration':'20','TotalWaitDuration':'25','ANI':'0612345678','DNIS':'','OutTel':'','OutDialed':'',
        'FirstAgent':'1001','LastAgent':'1001','FirstQueue':'501','LastQueue':'501','FirstCampaign':'C1','LastCampaign':'C1',
        'LastTransfer':'','EndReason':'','NoAgent':'0','Abandon':'0','Closed':'0','EndByAgent':'1'})
    rel=io.StringIO(); w=csv.DictWriter(rel,fieldnames=['CallID','RefCallID','Reason'],delimiter=';'); w.writeheader(); w.writerow({'CallID':'CALL-1','RefCallID':'PARENT-1','Reason':'3'})
    meanings=io.StringIO(); w=csv.DictWriter(meanings,fieldnames=['ReasonID','Description'],delimiter=';'); w.writeheader(); w.writerow({'ReasonID':'3','Description':'Internal consultation'})
    blob=io.BytesIO()
    with zipfile.ZipFile(blob,'w') as z:
        z.writestr('SIMPLIFY2.2026-09-18.Stats.AGENT.csv',stats.getvalue())
        z.writestr('SIMPLIFY2.2026-09-18.ODCalls.csv',calls.getvalue())
        z.writestr('SIMPLIFY2.2026-09-18.ODRelations.csv',rel.getvalue())
        z.writestr('SIMPLIFY2.2026-09-18.CallRelationMeaning.csv',meanings.getvalue())
    raw=blob.getvalue()
    first=import_export(raw,'SIMPLIFY2.2026-09-18.export.zip',120,'tester')
    assert first['duplicate'] is False and first['calls']==1 and first['call_details']==1 and first['call_relations']==1
    with connect() as c:
        assert c.execute('SELECT COUNT(*) FROM phone_calls').fetchone()[0]==1
        row=c.execute('SELECT first_queue,wait_initial,call_duration FROM phone_call_details WHERE call_id=?',('CALL-1',)).fetchone()
        assert tuple(row)==('501',20.0,110.0)
        relrow=c.execute('SELECT reason_code,reason_label FROM phone_call_relations WHERE call_id=?',('CALL-1',)).fetchone()
        assert tuple(relrow)==('3','Internal consultation')
        c.execute('DELETE FROM phone_call_details WHERE call_id=?',('CALL-1',))
        c.execute('DELETE FROM phone_call_relations WHERE call_id=?',('CALL-1',))
        c.execute('DELETE FROM phone_call_relation_imports WHERE import_id=?',(first['import_id'],))
    second=import_export(raw,'SIMPLIFY2.2026-09-18.export.zip',120,'tester')
    assert second['duplicate'] is True and second['calls']==0 and second['call_details']==1 and second['call_relations']==1
    with connect() as c:
        assert c.execute('SELECT COUNT(*) FROM phone_calls').fetchone()[0]==1
        row=c.execute('SELECT first_queue,last_campaign,wait_initial FROM phone_call_details WHERE call_id=?',('CALL-1',)).fetchone()
        assert tuple(row)==('501','C1',20.0)
        relrow=c.execute('SELECT reason_code,reason_label FROM phone_call_relations WHERE call_id=?',('CALL-1',)).fetchone()
        assert tuple(relrow)==('3','Internal consultation')

def test_live_admin_diagnostic_reports_only_measured_health(lab,monkeypatch):
    store,clock,_=_seed_live_observations(lab,monkeypatch)
    import service_mode
    monkeypatch.setattr(service_mode,'external_services_enabled',lambda:False)
    out=store.live_admin_diagnostic(clock=clock)
    assert out['collector']['ok'] is True and out['collector']['state']=='live'
    assert out['hermes']['ok'] is True and out['hermes']['last_response'] is not None
    assert out['worker']['measured'] is False and out['worker']['ok'] is None
    assert out['database']['ok'] is True and out['database']['engine'].startswith('SQLite')
    assert out['events']['last_event'] is not None and out['events']['pending']>=1
    assert out['clients_live_connected'] is None
    assert out['capabilities']['clients_live_connected'] is False
    assert 'pas mesuré' in out['limitations'][0]


def test_live_admin_diagnostic_reflects_external_worker_failure(lab,monkeypatch):
    store,clock,_=_seed_live_observations(lab,monkeypatch)
    import service_mode,service_state
    monkeypatch.setattr(service_mode,'external_services_enabled',lambda:True)
    monkeypatch.setattr(service_state,'public_status',lambda:{'services':[{'service':'live','healthy':False,'state':'stopped','age_seconds':25.0,'build_match':True}]})
    out=store.live_admin_diagnostic(clock=clock)
    assert out['collector']['state']=='worker_down' and out['collector']['ok'] is False
    assert out['worker']['measured'] is True and out['worker']['ok'] is False
    assert out['hermes']['ok'] is False

def test_pilotage_global_alerts_use_independent_service_baselines(lab,monkeypatch):
    """The global cockpit may show global KPIs, but alerts never blend parent services."""
    from supervision_db import init,connect
    from quality_metrics import ingest_inbound
    import pilotage_quality as pq
    init()
    groups=[
        {'id':'MED1','name':'MED1','service_name':'MEDICAL','member_agent_ids':['1001'],'campaign_ids':['A'],'line_ids':[],'file_count':0,'matched_file_count':0},
        {'id':'IMG1','name':'IMG1','service_name':'IMAGERIE','member_agent_ids':['2001'],'campaign_ids':['B'],'line_ids':[],'file_count':0,'matched_file_count':0},
    ]
    monkeypatch.setattr(pq,'_catalog',lambda:(groups,['IMAGERIE','MEDICAL']))
    def put(day,iid,med_t,med_a,img_t=90,img_a=10):
        rows=[]
        for _ in range(med_t):
            r=inbound_row('09:00:00',agent='S1001',campaign='A',answered=1);r['Date']=day+' 09:00:00';rows.append(r)
        for _ in range(med_a):
            r=inbound_row('09:05:00',agent='S0',campaign='A',abandoned=1);r['Date']=day+' 09:05:00';rows.append(r)
        for _ in range(img_t):
            r=inbound_row('10:00:00',agent='S2001',campaign='B',answered=1);r['Date']=day+' 10:00:00';rows.append(r)
        for _ in range(img_a):
            r=inbound_row('10:05:00',agent='S0',campaign='B',abandoned=1);r['Date']=day+' 10:05:00';rows.append(r)
        ingest_inbound(archive('Stats.INBOUND',rows),f'SIMPLIFY2.{day}.zip',iid,120)
        with connect() as c:c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',(day,iid))
    put('2026-09-04',1,90,10);put('2026-09-11',2,90,10);put('2026-09-18',3,50,50)
    out=pq.view({'day':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00'],'min_volume':['30']})
    assert out['signal_scope_mode']=='per_service'
    assert out['signals'] and {x.get('scope_label') for x in out['signals']}=={'MEDICAL'}
    assert all(x.get('service_name')!='IMAGERIE' for x in out['signals'])
    assert out['reliability']['service_assignment_percent']==100

def test_suspicious_calls_annotate_governance_without_deleting_evidence(lab):
    import app_db
    from supervision_db import connect,config,init
    from supervision_utils import selected_bounds
    from policy_admin import save_policy
    from suspicious_calls import view
    init();app_db.ensure_schema()
    qs={'date_from':['2026-09-18'],'date_to':['2026-09-18'],'time_from':['08:00'],'time_to':['19:00'],'category':['short']}
    lo,_=selected_bounds('2026-09-18',config(),qs,'0')
    with connect() as c:
        c.execute('INSERT INTO phone_calls VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',
                  (1,'governed-short','I1',lo+3600,'1',5,4,1,'0611111111','','','','1001','1001','C1','',0,0,0,1))
        c.execute('INSERT INTO phone_call_details VALUES(?,?,?,?,?,?,?,?,?,?)',
                  (1,'governed-short',5,1,1,'501','501','C1','C1',''))
        c.execute('INSERT OR REPLACE INTO call_coverage(day,import_id) VALUES(?,?)',('2026-09-18',1))
    save_policy({'name':'Autorisation test suspect','policy_type':'AUTORISATION','enabled':True,
                 'date_from':'2026-09-18','date_to':'2026-09-18','time_from':'08:55','time_to':'09:10',
                 'actions':{'exclude_statistics':True},'modules':['analytics'],
                 'targets':[{'target_type':'GLOBAL','target_key':'*'}]},'tester')
    out=view(qs)
    assert out['count']==1 and out['rows'][0]['governance_excluded'] is True
    assert 'Policy:' in out['rows'][0]['governance_reason']
    assert any('n’effacent pas la preuve brute' in x for x in out['limitations'])

def _finish_seeded_live_call(store,clock,sid):
    payload={'agent':'1001','observation_ref':'1001-1','phase':'left_call','next_state':'Prêt',
             'end_counters':{},'source_function':'UpAgtTState'}
    result=store.record_response(sid,'simplify',clock+2,'r3','digest-r3',
        {'recognized':1,'rejected':0,'events':[{'type':'call_update','entity':'1001','payload':payload}],'valid':True})
    assert result['accepted'] is True


def test_finalized_live_history_is_idempotent_and_excludes_ani(lab,monkeypatch):
    store,clock,sid=_seed_live_observations(lab,monkeypatch)
    _finish_seeded_live_call(store,clock,sid)
    out=store.persist_finalized_history()
    assert out['persisted']==1 and out['pending_finalized']==0
    from supervision_db import connect
    with connect() as c:
        row=c.execute('SELECT * FROM live_call_observation_history').fetchone()
        assert row is not None
        assert row['business_day']=='2026-09-18' and row['agent']=='1001'
        assert row['line_id']=='12' and row['campaign']=='CAB'
        assert row['observation_ref']=='1001-1' and row['final_status']=='left_call'
        cols={r[1] for r in c.execute('PRAGMA table_info(live_call_observation_history)')}
        assert 'ani' not in cols and 'phone' not in cols and 'call_id' not in cols
        assert '0612345678' not in '|'.join(str(row[k] or '') for k in row.keys())
    again=store.persist_finalized_history()
    assert again['persisted']==0
    with connect() as c:
        assert c.execute('SELECT COUNT(*) FROM live_call_observation_history').fetchone()[0]==1


def test_live_history_database_failure_keeps_local_evidence_unsynced(lab,monkeypatch):
    store,clock,sid=_seed_live_observations(lab,monkeypatch)
    _finish_seeded_live_call(store,clock,sid)
    import supervision_db
    def fail_connect():
        raise RuntimeError('historical database unavailable')
    monkeypatch.setattr(supervision_db,'connect',fail_connect)
    with pytest.raises(RuntimeError,match='historical database unavailable'):
        store.persist_finalized_history()
    status=store.live_history_sync_status()
    assert status['pending_finalized']==1 and status['synced_local']==0


def test_live_retention_defers_unsynced_then_purges_after_persistence(lab,monkeypatch):
    store,clock,sid=_seed_live_observations(lab,monkeypatch)
    _finish_seeded_live_call(store,clock,sid)
    before=store.purge_before_day('2026-09-19')
    assert before['deferred_unsynced']==1 and sid in before['deferred_sessions']
    assert store.session(sid) is not None
    synced=store.persist_finalized_history()
    assert synced['persisted']==1
    after=store.purge_before_day('2026-09-19')
    assert after['deferred_unsynced']==0 and after['deleted']['sessions']==1
    assert store.session(sid) is None


def test_recording_sync_scans_frames_and_waits_while_edge_is_open():
    root=Path(__file__).resolve().parent
    src=(root/'recording_sizes.py').read_text(encoding='utf-8')
    bat=(root/'SYNC_RECORDING_SIZES.bat').read_text(encoding='utf-8')
    assert "w.frames" in src and "performance?.getEntriesByType('resource')" in src
    assert "ouvrez maintenant Enregistrements UNE seule fois" in src
    assert "relancez la synchronisation" not in src
    assert "laissez cette fenetre ouverte" in bat.lower()
    assert "restez au niveau des SDA/campagnes" in bat
    assert "cliquez UNE seule fois sur le jour" not in bat


def test_recording_sync_recurses_and_probes_known_missing_agents():
    from recording_sizes import collect_day
    import json

    day='12139733\\2026\\09\\18'
    payloads={
      day:{'FolderList':['1001'],'FileList':[]},
      day+'\\1001':{'FolderList':['nested'],'FileList':[]},
      day+'\\1001\\nested':{'FolderList':[],'FileList':[
        {'Name':'1001#20260918#090000#IDX-A.wav','Size':800000},
      ]},
      # Agent 1002 is deliberately absent from the day FolderList.  The
      # catalogue fallback must still probe it and discover its WAV.
      day+'\\1002':{'FolderList':[],'FileList':[
        {'Name':'1002#20260918#100000#IDX-B.wav','Size':400000},
      ]},
      day+'\\1003':{'FolderList':[],'FileList':[]},
    }
    class Browser:
        def __init__(self):self.paths=[]
        def post_json(self,seed,path):
            self.paths.append(path)
            return json.dumps(payloads.get(path,{'FolderList':[],'FileList':[]}))
    browser=Browser()
    rows,stats=collect_day(browser,{'root':'12139733'},day,agent_ids=['1001','1002','1003'],pause=0)
    assert {x['indice'] for x in rows}=={'IDX-A','IDX-B'}
    assert day+'\\1001\\nested' in browser.paths
    assert day+'\\1002' in browser.paths
    assert stats['agents_probed']==2
    assert stats['agents_with_wav']==1


def test_recording_sync_uses_exact_day_anchor_payload_without_refetching_day():
    from recording_sizes import collect_day
    import json
    day='12139733\\2026\\09\\18'
    anchor=json.dumps({'FolderList':['1001','1002'],'FileList':[]})
    payloads={
      day+'\\1001':{'FolderList':[],'FileList':[{'Name':'1001#20260918#090000#IDX-1.wav','Size':800000}]},
      day+'\\1002':{'FolderList':[],'FileList':[{'Name':'1002#20260918#100000#IDX-2.wav','Size':400000}]},
    }
    class Browser:
        def __init__(self):self.paths=[]
        def post_json(self,seed,path):
            self.paths.append(path)
            return json.dumps(payloads.get(path,{'FolderList':[],'FileList':[]}))
    browser=Browser()
    rows,stats=collect_day(browser,{'root':'12139733'},day,agent_ids=[],pause=0,initial_payload=anchor)
    assert day not in browser.paths
    assert {x['indice'] for x in rows}=={'IDX-1','IDX-2'}
    assert stats['anchor_folders']==2 and stats['anchor_files']==0


def test_recording_root_label_parser_ignores_agent_and_call_indices():
    from recording_sizes import _root_id
    assert _root_id('76430929 - CH GISORS',require_label=True)=='76430929'
    assert _root_id('76431213 - CIMVES-HABERGES',require_label=True)=='76431213'
    assert _root_id('1031',require_label=True)==''
    assert _root_id('781913581',require_label=True)==''


def test_recording_sync_scans_all_record_roots_without_day_click(monkeypatch):
    import json
    import recording_sizes as rs

    root_a='76430929'
    root_b='76431213'
    day_suffix='2026\\09\\18'
    day_a=root_a+'\\'+day_suffix
    day_b=root_b+'\\'+day_suffix
    payloads={
      day_a:{'FolderList':['1031'],'FileList':[]},
      day_a+'\\1031':{'FolderList':[],'FileList':[
        {'Name':'1031#20260918#090000#781900001.wav','Size':419440},
      ]},
      day_b:{'FolderList':['1066'],'FileList':[]},
      day_b+'\\1066':{'FolderList':[],'FileList':[
        {'Name':'1066#20260918#100000#781900002.wav','Size':905340},
      ]},
    }

    class FakeBrowser:
        def __init__(self,*a,**k):self.paths=[]
        def __enter__(self):return self
        def __exit__(self,*a):return False
        def wait_seed(self):
            return {'root':'','params':{},'uid':'u','idCompany':'231','origin':'https://example.test'}
        def discover_recording_roots(self,seed,anchor_path=''):
            assert anchor_path==''
            return [root_a,root_b]
        def post_json(self,seed,path):
            self.paths.append(path)
            return json.dumps(payloads.get(path,{'FolderList':[],'FileList':[]}))

    monkeypatch.setattr(rs,'BrowserSession',FakeBrowser)
    monkeypatch.setattr(rs,'known_recording_agents',lambda:[])
    monkeypatch.setattr(rs,'store',lambda rows:len(rows))
    out=rs.sync('2026-09-18','2026-09-18',pause=0)
    assert out['roots_detected']==2
    assert out['roots_with_wav']==2
    assert out['agent_folders_scanned']==2
    assert out['files']==2 and out['stored']==2
    assert {r['indice'] for r in out['rows']}=={'781900001','781900002'}


def test_recording_extract_seed_accepts_record_root_listing():
    from recording_sizes import extract_seed
    url=('https://example.test/hermes360/Supervision/changes.ashx?act=folder_info&uid=abc'
         '&idCompany=231&extension=*.wav&basePath=RECORD&subPath=&filters=')
    seed=extract_seed([url])
    assert seed is not None
    assert seed['uid']=='abc' and seed['idCompany']=='231'
    assert seed['root']==''

def test_recording_root_discovery_merges_anchor_server_dom_and_resources(monkeypatch):
    import json
    from recording_sizes import BrowserSession
    b=BrowserSession()
    b.resource_urls=lambda:[
      'https://example.test/hermes360/Supervision/changes.ashx?act=folder_info&uid=u&idCompany=231&extension=*.wav&basePath=RECORD&subPath=12139733%5C2026%5C09&filters='
    ]
    b.post_json=lambda seed,path: json.dumps({'FolderList':['76430929 - CH GISORS','76431213 - CIMVES-HABERGES'],'FileList':[]})
    b.recording_root_ids_from_dom=lambda:['76430994','76431213']
    roots=b.discover_recording_roots({'root':'12139733','params':{},'uid':'u','idCompany':'231','origin':'https://example.test'},'12139733\\2026\\09\\18')
    assert set(roots)=={'12139733','76430929','76430994','76431213'}



def test_recording_rc12_persists_only_verified_indice_and_size(lab):
    import recording_sizes as rs
    from supervision_db import connect, init
    init()
    with connect() as c:
        c.execute("INSERT INTO imports(id,digest,name,reference_day,offset_minutes) VALUES(1,'d1','SIMPLIFY2.2026-09-18.export.zip','2026-09-18',120)")
        for call_id,indice,agent in [('C1','IDX-1','1001'),('C2','IDX-2','1002')]:
            c.execute("INSERT INTO phone_calls(import_id,call_id,indice,start,call_type,duration,conversation,wait,ani,dnis,outtel,outdialed,first_agent,last_agent,campaign,end_reason,no_agent,abandon,closed,end_by_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
              (1,call_id,indice,0,1,60,60,0,'','','','',agent,agent,'','',0,0,0,0))
        c.commit()
    rows=[
      rs.parse_file({'Name':'1001#20260918#090000#IDX-1.wav','Size':100000}),
      rs.parse_file({'Name':'1001#20260918#090100#IDX-1.wav','Size':200000}),
      rs.parse_file({'Name':'1002#20260918#100000#IDX-2.wav','Size':400000}),
    ]
    assert rs.store(rows)==2
    with connect() as c:
        cols=[r[1] for r in c.execute('PRAGMA table_info(call_recording_sizes)')]
        assert cols==['indice','size_bytes']
        got={str(r[0]):int(r[1]) for r in c.execute('SELECT indice,size_bytes FROM call_recording_sizes')}
    assert got['IDX-1']==300000 and got['IDX-2']==400000


def test_recording_rc12_rejects_unverified_sizes(lab):
    import recording_sizes as rs
    from supervision_db import connect, init
    init()
    with connect() as c:
        c.execute("INSERT INTO imports(id,digest,name,reference_day,offset_minutes) VALUES(1,'d1','SIMPLIFY2.2026-09-18.export.zip','2026-09-18',120)")
        for call_id,indice,conversation,agent in [('C0','ZERO',0,'1001'),('C1','WRONGDAY',60,'1001'),('C2','WRONGAGENT',60,'1001')]:
            c.execute("INSERT INTO phone_calls(import_id,call_id,indice,start,call_type,duration,conversation,wait,ani,dnis,outtel,outdialed,first_agent,last_agent,campaign,end_reason,no_agent,abandon,closed,end_by_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
              (1,call_id,indice,0,1,120,conversation,0,'','','','',agent,agent,'','',0,0,0,0))
        c.commit()
    rows=[
      rs.parse_file({'Name':'1001#20260918#090000#MISSING.wav','Size':100000}),
      rs.parse_file({'Name':'1001#20260918#090000#ZERO.wav','Size':100000}),
      rs.parse_file({'Name':'1001#20260919#090000#WRONGDAY.wav','Size':100000}),
      rs.parse_file({'Name':'1002#20260918#090000#WRONGAGENT.wav','Size':100000}),
    ]
    assert rs.store(rows)==0
    with connect() as c:
        assert c.execute('SELECT COUNT(*) FROM call_recording_sizes').fetchone()[0]==0

def test_recording_rc10_discovers_all_history_days():
    import json
    from recording_sizes import discover_history_days
    payloads={
      '76430001':{'FolderList':['2025','2026'],'FileList':[]},
      '76430001\\2025':{'FolderList':['12'],'FileList':[]},
      '76430001\\2025\\12':{'FolderList':['31'],'FileList':[]},
      '76430001\\2026':{'FolderList':['09'],'FileList':[]},
      '76430001\\2026\\09':{'FolderList':['18','19'],'FileList':[]},
      '76430002':{'FolderList':['2026'],'FileList':[]},
      '76430002\\2026':{'FolderList':['09'],'FileList':[]},
      '76430002\\2026\\09':{'FolderList':['18'],'FileList':[]},
    }
    class Browser:
        def post_json(self,seed,path):
            return json.dumps(payloads.get(path,{'FolderList':[],'FileList':[]}))
    days,requests=discover_history_days(Browser(),{},['76430001','76430002'],pause=0)
    assert set(days)=={'2025-12-31','2026-09-18','2026-09-19'}
    assert set(days['2026-09-18'])=={'76430001','76430002'}
    assert requests==8


def test_recording_rc10_all_history_scans_every_discovered_day(monkeypatch):
    import json
    import recording_sizes as rs
    roots=['76430001','76430002']
    history={'2026-08-31':['76430001'],'2026-09-18':['76430001','76430002']}
    payloads={
      '76430001\\2026\\08\\31':{'FolderList':['1001'],'FileList':[]},
      '76430001\\2026\\08\\31\\1001':{'FolderList':[],'FileList':[{'Name':'1001#20260831#090000#IDX-A.wav','Size':100000}]},
      '76430001\\2026\\09\\18':{'FolderList':['1001'],'FileList':[]},
      '76430001\\2026\\09\\18\\1001':{'FolderList':[],'FileList':[{'Name':'1001#20260918#100000#IDX-B.wav','Size':200000}]},
      '76430002\\2026\\09\\18':{'FolderList':['1002'],'FileList':[]},
      '76430002\\2026\\09\\18\\1002':{'FolderList':[],'FileList':[{'Name':'1002#20260918#100500#IDX-B.wav','Size':300000}]},
    }
    class FakeBrowser:
        def __init__(self,*a,**k):pass
        def __enter__(self):return self
        def __exit__(self,*a):return False
        def wait_seed(self):return {'root':'','params':{},'uid':'u','idCompany':'231','origin':'https://example.test'}
        def discover_recording_roots(self,seed,anchor_path=''):return roots
        def post_json(self,seed,path):return json.dumps(payloads.get(path,{'FolderList':[],'FileList':[]}))
    stored=[]
    monkeypatch.setattr(rs,'BrowserSession',FakeBrowser)
    monkeypatch.setattr(rs,'discover_history_days',lambda browser,seed,roots,pause=0:(history,7))
    monkeypatch.setattr(rs,'_load_sync_state',lambda:{'completed_days':set()})
    monkeypatch.setattr(rs,'_save_sync_state',lambda state:None)
    def fake_store(rows,**kw):
        totals,_=rs._aggregate_sizes(rows);stored.append(dict(totals));return len(totals)
    monkeypatch.setattr(rs,'store',fake_store)
    out=rs.sync_all(pause=0,resume=True)
    assert out['days_detected']==2 and out['days_processed']==2 and out['days_skipped']==0
    assert stored[0]=={'IDX-A':100000}
    assert stored[1]=={'IDX-B':500000}


def test_suspicious_size_requires_positive_conversation():
    import suspicious_calls as sc
    cfg={"recording_reference_bps":8000,"recording_low_percent":60,"recording_critical_percent":35,"recording_min_seconds":30}
    row={
        "call_duration":377, "duration":377, "conversation":0,
        "hold_duration":0, "complex_flow":False,
        "media_seconds":0, "media_density_bps":0,
        "end_by_agent":0,
    }
    reasons=sc._reasons(row,False,cfg)
    assert not any("size" in r.lower() for r in reasons)
    sql=sc._category_sql("low_content",cfg)
    assert "COALESCE(p.conversation,0)>=" in sql
    assert "CASE WHEN COALESCE(p.conversation,0)>0" not in sql
