from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DBS = {
    'admin': ROOT / 'TECHIN_Stock_Manager.db',
    'supervision': ROOT / 'NELYIO_Supervision.db',
    'details': ROOT / 'Nelyio_Details.db',
    # V60: Live stays in its own local SQLite/WAL database and is never
    # migrated into PostgreSQL.
}


def load_env():
    env = ROOT / 'data' / 'postgres.env'
    if env.is_file():
        for raw in env.read_text(encoding='utf-8-sig').splitlines():
            line = raw.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            k, v = line.split('=', 1)
            os.environ.setdefault(k.strip(), v.strip())
    return env


def pg_type(declared: str) -> str:
    t = (declared or '').upper()
    if 'INT' in t:
        return 'BIGINT'
    if any(x in t for x in ('REAL', 'FLOA', 'DOUB')):
        return 'DOUBLE PRECISION'
    if 'BLOB' in t:
        return 'BYTEA'
    if any(x in t for x in ('NUM', 'DEC')):
        return 'NUMERIC'
    return 'TEXT'


def qident(name: str) -> str:
    return '"' + str(name).replace('"', '""') + '"'


def table_sql(src: sqlite3.Connection, schema: str, table: str):
    info = src.execute(f'PRAGMA table_info({qident(table)})').fetchall()
    src_sql_row = src.execute("SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone()
    src_sql = src_sql_row[0] if src_sql_row and src_sql_row[0] else ''
    pk_cols = [r[1] for r in sorted((r for r in info if r[5]), key=lambda x: x[5])]
    single_integer_pk = len(pk_cols) == 1 and next((r for r in info if r[1] == pk_cols[0] and 'INT' in (r[2] or '').upper()), None) is not None
    cols = []
    for cid, name, dtype, notnull, default, pkpos in info:
        typ = pg_type(dtype)
        if single_integer_pk and name == pk_cols[0]:
            col = f'{qident(name)} BIGINT GENERATED BY DEFAULT AS IDENTITY'
        else:
            col = f'{qident(name)} {typ}'
        if notnull:
            col += ' NOT NULL'
        if default is not None:
            d = str(default).strip()
            if re.fullmatch(r'CURRENT_TIMESTAMP', d, re.I):
                col += ' DEFAULT CURRENT_TIMESTAMP'
            elif re.fullmatch(r'[-+]?\d+(?:\.\d+)?', d):
                col += ' DEFAULT ' + d
            elif d.upper() in {'NULL', 'TRUE', 'FALSE'}:
                col += ' DEFAULT ' + d.upper()
            elif (d.startswith("'") and d.endswith("'")) or (d.startswith('"') and d.endswith('"')):
                col += ' DEFAULT ' + d.replace('"', "'")
        cols.append(col)
    if pk_cols:
        cols.append('PRIMARY KEY (' + ','.join(qident(c) for c in pk_cols) + ')')
    sql = f'CREATE TABLE {qident(schema)}.{qident(table)} (\n  ' + ',\n  '.join(cols) + '\n)'
    return sql, info, pk_cols, single_integer_pk, src_sql



def prepare_sqlite_sources():
    """Bring legacy SQLite files to the latest shipped schema before copying."""
    old_url=os.environ.pop('NELYIO_DATABASE_URL',None)
    old_engine=os.environ.pop('NELYIO_DATABASE_ENGINE',None)
    old_skip=os.environ.get('NELYIO_SKIP_STARTUP_DETAILS_SYNC')
    old_force=os.environ.get('NELYIO_FORCE_SQLITE')
    os.environ['NELYIO_SKIP_STARTUP_DETAILS_SYNC']='1'
    os.environ['NELYIO_FORCE_SQLITE']='1'
    try:
        import app, details_store, collection_store
        import quality_metrics, quality_agents, import_workflow, group_har_import
        from supervision_db import connect as supervision_connect
        app.ensure_schema()
        app.supervision.init()
        details_store.init()
        collection_store.init(force=True)
        # Materialize lazy schemas before the PostgreSQL copy.  This avoids
        # relying on SQLite DDL translation during the first production request
        # (notably Qualite and import-job tables).
        with supervision_connect() as con:
            quality_metrics.ensure_schema(con)
            quality_agents.ensure_schema(con)
            import_workflow.ensure_schema(con)
        with app.db_connect() as con:
            group_har_import.ensure_schema(con)
    finally:
        if old_url is not None: os.environ['NELYIO_DATABASE_URL']=old_url
        if old_engine is not None: os.environ['NELYIO_DATABASE_ENGINE']=old_engine
        if old_skip is None: os.environ.pop('NELYIO_SKIP_STARTUP_DETAILS_SYNC',None)
        else: os.environ['NELYIO_SKIP_STARTUP_DETAILS_SYNC']=old_skip
        if old_force is None: os.environ.pop('NELYIO_FORCE_SQLITE',None)
        else: os.environ['NELYIO_FORCE_SQLITE']=old_force


def create_helpers(con):
    helpers = r'''
-- PostgreSQL has no SQLite rowid. Keep a durable insertion sequence for the
-- two append-only streams consumed incrementally by Details.
ALTER TABLE supervision.live_events ADD COLUMN IF NOT EXISTS ingest_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE supervision.technical_signals ADD COLUMN IF NOT EXISTS ingest_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS supervision_live_events_ingest_seq ON supervision.live_events(ingest_seq);
CREATE UNIQUE INDEX IF NOT EXISTS supervision_technical_signals_ingest_seq ON supervision.technical_signals(ingest_seq);
CREATE INDEX IF NOT EXISTS supervision_quality_inbound_day ON supervision.quality_inbound_facts(import_id,day,campaign,start);
CREATE INDEX IF NOT EXISTS supervision_quality_inbound_selected ON supervision.quality_inbound_facts(import_id,day,start);
CREATE INDEX IF NOT EXISTS supervision_quality_inbound_agent_selected ON supervision.quality_inbound_facts(import_id,day,agent,start);
CREATE INDEX IF NOT EXISTS supervision_quality_outbound_selected ON supervision.quality_outbound_facts(import_id,day,start);
CREATE INDEX IF NOT EXISTS supervision_quality_outbound_agent_selected ON supervision.quality_outbound_facts(import_id,day,agent,start);
CREATE INDEX IF NOT EXISTS supervision_quality_agent_time ON supervision.quality_agent_facts(import_id,start,"end",agent);
CREATE INDEX IF NOT EXISTS supervision_quality_agent_selected ON supervision.quality_agent_facts(import_id,agent,start,"end");
CREATE INDEX IF NOT EXISTS supervision_quality_call_holds_session ON supervision.quality_call_holds(import_id,call_id);
CREATE INDEX IF NOT EXISTS supervision_activity_import_agent_time ON supervision.activities(import_id,agent,start,"end");
CREATE INDEX IF NOT EXISTS supervision_calls_import_agent_time ON supervision.phone_calls(import_id,first_agent,start);
CREATE INDEX IF NOT EXISTS supervision_calls_import_last_agent_time ON supervision.phone_calls(import_id,last_agent,start);
CREATE INDEX IF NOT EXISTS supervision_calls_import_campaign_time ON supervision.phone_calls(import_id,campaign,start);
CREATE INDEX IF NOT EXISTS supervision_call_details_queue ON supervision.phone_call_details(import_id,first_queue);
CREATE INDEX IF NOT EXISTS supervision_call_details_transfer ON supervision.phone_call_details(import_id,last_transfer);
CREATE INDEX IF NOT EXISTS supervision_call_relations_call ON supervision.phone_call_relations(import_id,call_id);
CREATE INDEX IF NOT EXISTS supervision_call_relations_ref ON supervision.phone_call_relations(import_id,ref_call_id);
CREATE INDEX IF NOT EXISTS supervision_call_recordings_indice ON supervision.call_recordings(indice);
CREATE INDEX IF NOT EXISTS supervision_call_recordings_day_agent ON supervision.call_recordings(recorded_day,agent);

CREATE OR REPLACE FUNCTION public.user_key(value text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT upper(trim(split_part(regexp_replace(coalesce(value,''), '^.*[\\/]', ''), '@', 1)))
$$;

CREATE OR REPLACE FUNCTION public.ip_match(ip_text text, selector text) RETURNS bigint
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE a inet; lo inet; hi inet; p text[];
BEGIN
  IF coalesce(trim(ip_text),'')='' OR coalesce(trim(selector),'')='' THEN RETURN 0; END IF;
  BEGIN a := trim(ip_text)::inet; EXCEPTION WHEN others THEN RETURN 0; END;
  IF position('..' in selector)>0 THEN
    p := string_to_array(selector,'..');
    BEGIN lo:=trim(p[1])::inet; hi:=trim(p[2])::inet; EXCEPTION WHEN others THEN RETURN 0; END;
    RETURN CASE WHEN a >= lo AND a <= hi THEN 1 ELSE 0 END;
  ELSIF position('-' in selector)>0 AND position('/' in selector)=0 THEN
    p := string_to_array(selector,'-');
    BEGIN lo:=trim(p[1])::inet; hi:=trim(p[2])::inet; EXCEPTION WHEN others THEN RETURN 0; END;
    RETURN CASE WHEN a >= lo AND a <= hi THEN 1 ELSE 0 END;
  ELSE
    BEGIN RETURN CASE WHEN a <<= trim(selector)::inet THEN 1 ELSE 0 END;
    EXCEPTION WHEN others THEN
      BEGIN RETURN CASE WHEN a = trim(selector)::inet THEN 1 ELSE 0 END; EXCEPTION WHEN others THEN RETURN 0; END;
    END;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.classify_site(collector_text text, ip_text text, gateway_text text DEFAULT '') RETURNS text
LANGUAGE plpgsql STABLE AS $$
DECLARE r record; c text := upper(coalesce(nullif(trim(collector_text),''),'*')); fallback text;
BEGIN
  FOR r IN SELECT network,gateway_network,result_site FROM admin.site_rules
           WHERE enabled=1 AND upper(coalesce(nullif(trim(collector),''),'*')) IN (c,'*')
           ORDER BY priority DESC,id ASC LOOP
    IF public.ip_match(ip_text,r.network)=1 AND (coalesce(trim(r.gateway_network),'')='' OR public.ip_match(gateway_text,r.gateway_network)=1) THEN
      RETURN r.result_site;
    END IF;
  END LOOP;
  SELECT default_site INTO fallback FROM admin.site_policies WHERE upper(collector)=c LIMIT 1;
  IF fallback IS NULL THEN SELECT default_site INTO fallback FROM admin.site_policies WHERE collector='*' LIMIT 1; END IF;
  RETURN coalesce(fallback,'INCONNU');
END $$;

CREATE OR REPLACE FUNCTION public.classify_site(collector_text text, ip_text text) RETURNS text
LANGUAGE sql STABLE AS $$ SELECT public.classify_site(collector_text,ip_text,'') $$;

CREATE OR REPLACE FUNCTION public.classify_reason(collector_text text, ip_text text, gateway_text text DEFAULT '') RETURNS text
LANGUAGE plpgsql STABLE AS $$
DECLARE r record; c text := upper(coalesce(nullif(trim(collector_text),''),'*'));
BEGIN
  FOR r IN SELECT network,gateway_network,label,result_site FROM admin.site_rules
           WHERE enabled=1 AND upper(coalesce(nullif(trim(collector),''),'*')) IN (c,'*')
           ORDER BY priority DESC,id ASC LOOP
    IF public.ip_match(ip_text,r.network)=1 AND (coalesce(trim(r.gateway_network),'')='' OR public.ip_match(gateway_text,r.gateway_network)=1) THEN
      RETURN coalesce(nullif(r.label,''),r.network) || CASE WHEN coalesce(trim(r.gateway_network),'')<>'' THEN ' · GW '||r.gateway_network ELSE '' END;
    END IF;
  END LOOP;
  RETURN CASE WHEN c<>'*' THEN 'Défaut '||c ELSE 'Collecteur inconnu' END;
END $$;

CREATE OR REPLACE FUNCTION public.classify_reason(collector_text text, ip_text text) RETURNS text
LANGUAGE sql STABLE AS $$ SELECT public.classify_reason(collector_text,ip_text,'') $$;

CREATE OR REPLACE FUNCTION public.julianday(v date) RETURNS double precision
LANGUAGE sql IMMUTABLE AS $$ SELECT extract(epoch from v::timestamp)/86400.0 + 2440587.5 $$;
CREATE OR REPLACE FUNCTION public.julianday(v text) RETURNS double precision
LANGUAGE sql IMMUTABLE AS $$ SELECT public.julianday(v::date) $$;

CREATE OR REPLACE FUNCTION public.followup_status(admin_status text, days bigint, raw text) RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE j jsonb; item jsonb; override text;
BEGIN
  IF raw IS NULL OR trim(raw)='' THEN RETURN NULL; END IF;
  BEGIN j:=raw::jsonb; EXCEPTION WHEN others THEN RETURN NULL; END;
  override := j->'admin_overrides'->>coalesce(admin_status,'EN_SERVICE');
  IF override IS NOT NULL AND override<>'' AND override<>'null' THEN RETURN override; END IF;
  IF days IS NULL THEN RETURN coalesce(j->>'never_seen','CRITIQUE'); END IF;
  FOR item IN SELECT * FROM jsonb_array_elements(coalesce(j->'ranges','[]'::jsonb)) LOOP
    IF days >= coalesce((item->>'min_days')::bigint,0)
       AND ((item->>'max_days') IS NULL OR (item->>'max_days')='null' OR days <= (item->>'max_days')::bigint) THEN
      RETURN item->>'status';
    END IF;
  END LOOP;
  RETURN coalesce(j->>'never_seen','CRITIQUE');
END $$;

CREATE OR REPLACE FUNCTION public.strftime(fmt text, epoch_value double precision, modifier text DEFAULT '') RETURNS text
LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE pgfmt text;
BEGIN
  pgfmt := replace(replace(replace(replace(replace(fmt,'%Y','YYYY'),'%m','MM'),'%d','DD'),'%H','HH24'),'%M','MI');
  RETURN to_char(to_timestamp(epoch_value),pgfmt);
END $$;

CREATE OR REPLACE FUNCTION public.quality_local_hour(epoch_value double precision) RETURNS integer
LANGUAGE sql STABLE AS $$
  SELECT EXTRACT(HOUR FROM (to_timestamp(epoch_value) AT TIME ZONE 'Europe/Paris'))::integer
$$;

CREATE OR REPLACE FUNCTION public.distribution_hour(epoch_value double precision) RETURNS integer
LANGUAGE sql STABLE AS $$
  SELECT public.quality_local_hour(epoch_value)
$$;

CREATE OR REPLACE FUNCTION public.distribution_agent(value text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE
    WHEN public.user_key(value) IN ('', '0', 'S0') THEN ''
    WHEN public.user_key(value) ~ '^S[0-9]+$' THEN substr(public.user_key(value),2)
    ELSE public.user_key(value)
  END
$$;

CREATE OR REPLACE FUNCTION details.bump_detail_read_revision() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN UPDATE details.detail_read_revision SET version=version+1 WHERE id=1; RETURN NULL; END $$;
DROP TRIGGER IF EXISTS detail_read_events_insert ON details.detail_events;
DROP TRIGGER IF EXISTS detail_read_events_update ON details.detail_events;
DROP TRIGGER IF EXISTS detail_read_events_delete ON details.detail_events;
CREATE TRIGGER detail_read_events_insert AFTER INSERT ON details.detail_events FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_events_update AFTER UPDATE ON details.detail_events FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_events_delete AFTER DELETE ON details.detail_events FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
DROP TRIGGER IF EXISTS detail_read_agents_insert ON details.detail_event_agents;
DROP TRIGGER IF EXISTS detail_read_agents_update ON details.detail_event_agents;
DROP TRIGGER IF EXISTS detail_read_agents_delete ON details.detail_event_agents;
CREATE TRIGGER detail_read_agents_insert AFTER INSERT ON details.detail_event_agents FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_agents_update AFTER UPDATE ON details.detail_event_agents FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_agents_delete AFTER DELETE ON details.detail_event_agents FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
DROP TRIGGER IF EXISTS detail_read_days_insert ON details.active_days;
DROP TRIGGER IF EXISTS detail_read_days_update ON details.active_days;
DROP TRIGGER IF EXISTS detail_read_days_delete ON details.active_days;
CREATE TRIGGER detail_read_days_insert AFTER INSERT ON details.active_days FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_days_update AFTER UPDATE ON details.active_days
FOR EACH ROW WHEN (
  OLD.day IS DISTINCT FROM NEW.day OR
  OLD.source_kind IS DISTINCT FROM NEW.source_kind OR
  OLD.source_import_id IS DISTINCT FROM NEW.source_import_id
) EXECUTE FUNCTION details.bump_detail_read_revision();
CREATE TRIGGER detail_read_days_delete AFTER DELETE ON details.active_days FOR EACH STATEMENT EXECUTE FUNCTION details.bump_detail_read_revision();
'''
    with con.cursor() as cur:
        cur.execute(helpers)
    con.commit()


def migrate_schema(pg, schema: str, db_path: Path, reset: bool):
    if not db_path.is_file():
        print(f'[WARN] {db_path.name} absent; schema {schema} cree vide.')
        with pg.cursor() as cur:
            cur.execute(f'CREATE SCHEMA IF NOT EXISTS {qident(schema)}')
        pg.commit()
        return {'tables':0,'rows':0}
    src = sqlite3.connect(str(db_path))
    src.row_factory = sqlite3.Row
    tables = [r[0] for r in src.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
    with pg.cursor() as cur:
        if reset:
            cur.execute(f'DROP SCHEMA IF EXISTS {qident(schema)} CASCADE')
        cur.execute(f'CREATE SCHEMA IF NOT EXISTS {qident(schema)}')
    pg.commit()
    total_rows=0
    identity=[]
    for table in tables:
        ddl, info, pk_cols, is_identity, src_sql = table_sql(src,schema,table)
        with pg.cursor() as cur:
            cur.execute(f'DROP TABLE IF EXISTS {qident(schema)}.{qident(table)} CASCADE')
            cur.execute(ddl)
        pg.commit()
        cols=[r[1] for r in info]
        count=src.execute(f'SELECT COUNT(*) FROM {qident(table)}').fetchone()[0]
        if count:
            select_sql='SELECT '+','.join(qident(c) for c in cols)+' FROM '+qident(table)
            copy_sql='COPY '+qident(schema)+'.'+qident(table)+' ('+','.join(qident(c) for c in cols)+') FROM STDIN'
            with pg.cursor() as cur, cur.copy(copy_sql) as cp:
                for row in src.execute(select_sql):
                    cp.write_row(tuple(row[c] for c in cols))
            pg.commit()
        total_rows += count
        if is_identity and pk_cols:
            identity.append((table,pk_cols[0]))
        print(f'[OK] {schema}.{table}: {count} lignes')
    # recreate unique indexes before non-unique indexes
    for table in tables:
        for idx in src.execute(f'PRAGMA index_list({qident(table)})').fetchall():
            # seq,name,unique,origin,partial
            name=idx[1]; unique=bool(idx[2]); origin=idx[3] if len(idx)>3 else ''
            if origin=='pk': continue
            cols=[r[2] for r in src.execute(f'PRAGMA index_info({qident(name)})').fetchall() if r[2] is not None]
            if not cols: continue
            idxname=(schema+'_'+name)[:60]
            stmt='CREATE '+('UNIQUE ' if unique else '')+'INDEX IF NOT EXISTS '+qident(idxname)+' ON '+qident(schema)+'.'+qident(table)+' ('+','.join(qident(c) for c in cols)+')'
            try:
                with pg.cursor() as cur: cur.execute(stmt)
                pg.commit()
            except Exception as exc:
                pg.rollback(); print(f'[WARN] index {schema}.{name}: {exc}')
    # Recreate SQLite foreign keys after all tables are loaded.
    for table in tables:
        groups={}
        for fk in src.execute(f'PRAGMA foreign_key_list({qident(table)})').fetchall():
            # id,seq,table,from,to,on_update,on_delete,match
            groups.setdefault(fk[0],[]).append(fk)
        for fid, rows in groups.items():
            rows=sorted(rows,key=lambda r:r[1])
            ref=rows[0][2]; from_cols=[r[3] for r in rows]; to_cols=[r[4] for r in rows]
            on_update=(rows[0][5] or 'NO ACTION').upper(); on_delete=(rows[0][6] or 'NO ACTION').upper()
            cname=f'fk_{schema}_{table}_{fid}'[:60]
            stmt=(f'ALTER TABLE {qident(schema)}.{qident(table)} ADD CONSTRAINT {qident(cname)} '
                  f'FOREIGN KEY ({",".join(qident(c) for c in from_cols)}) REFERENCES {qident(schema)}.{qident(ref)} ({",".join(qident(c) for c in to_cols)}) '
                  f'ON UPDATE {on_update} ON DELETE {on_delete}')
            try:
                with pg.cursor() as cur: cur.execute(stmt)
                pg.commit()
            except Exception as exc:
                pg.rollback(); print(f'[WARN] FK {schema}.{table}: {exc}')

    # reset identity sequences after copied IDs
    for table, pk in identity:
        try:
            with pg.cursor() as cur:
                cur.execute("SELECT pg_get_serial_sequence(%s,%s)",(f'{schema}.{table}',pk)); seq=cur.fetchone()[0]
                if seq:
                    cur.execute(f'SELECT COALESCE(MAX({qident(pk)}),0) FROM {qident(schema)}.{qident(table)}'); mx=cur.fetchone()[0]
                    cur.execute('SELECT setval(%s,%s,%s)',(seq,max(1,int(mx)),bool(mx)))
            pg.commit()
        except Exception as exc:
            pg.rollback(); print(f'[WARN] sequence {schema}.{table}: {exc}')
    src.close()
    return {'tables':len(tables),'rows':total_rows}


def verify(pg, expected):
    mismatches=[]
    for schema, db_path in DBS.items():
        if not db_path.is_file(): continue
        src=sqlite3.connect(str(db_path))
        for (table,) in src.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"):
            a=src.execute(f'SELECT COUNT(*) FROM {qident(table)}').fetchone()[0]
            with pg.cursor() as cur:
                cur.execute(f'SELECT COUNT(*) FROM {qident(schema)}.{qident(table)}'); b=cur.fetchone()[0]
            if a!=b: mismatches.append((schema,table,a,b))
        src.close()
    return mismatches


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--reset',action='store_true',help='Recreer les 4 schemas PostgreSQL depuis les SQLite actuels')
    ap.add_argument('--verify-only',action='store_true')
    args=ap.parse_args()
    env=load_env()
    dsn=os.environ.get('NELYIO_DATABASE_URL','').strip()
    if not dsn:
        raise SystemExit('NELYIO_DATABASE_URL absent. Lancez CONFIGURER_POSTGRESQL_AUTO.bat.')
    try:
        import psycopg
    except ImportError:
        raise SystemExit('psycopg absent. Lancez: py -3 -m pip install "psycopg[binary]>=3.2,<4"')
    if not args.verify_only:
        prepare_sqlite_sources()
    pg=psycopg.connect(dsn)
    if not args.verify_only:
        summary={}
        for schema,path in DBS.items(): summary[schema]=migrate_schema(pg,schema,path,args.reset)
        create_helpers(pg)
        with pg.cursor() as cur:
            cur.execute('CREATE TABLE IF NOT EXISTS public.nelyio_migration_meta(key text PRIMARY KEY,value text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now())')
            cur.execute("INSERT INTO public.nelyio_migration_meta(key,value) VALUES('engine','postgresql') ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now()")
            cur.execute("INSERT INTO public.nelyio_migration_meta(key,value) VALUES('summary',%s) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now()",(json.dumps(summary,ensure_ascii=False),))
        pg.commit()
    mismatches=verify(pg,DBS)
    pg.close()
    if mismatches:
        print('[ERREUR] Comparaison SQLite/PostgreSQL:')
        for x in mismatches: print(' ',x)
        return 2
    print('[OK] Migration PostgreSQL verifiee: nombres de lignes identiques.')
    print('[OK] Les SQLite historiques peuvent etre conserves comme sauvegarde; Nelyio utilisera PostgreSQL.')
    return 0

if __name__=='__main__':
    raise SystemExit(main())
